# coding: utf-8
from store.models import Customer, Address, Category, Product, Order
customer1 = Customer.objects.create(name="Alice Johnson", email="alice@example.com")
customer2 = Customer.objects.create(name="Bob Smith", email="bob@example.com")
customer3 = Customer.objects.create(name="Charlie Brown", email="charlie@example.com")
customer4 = Customer.objects.create(name="David White", email="david@example.com")
customer5 = Customer.objects.create(name="Eve Black", email="eve@example.com")
Address.objects.create(customer=customer1, street="123 Maple St", city="New York", state="NY", zip_code="10001")
Address.objects.create(customer=customer2, street="456 Oak St", city="Los Angeles", state="CA", zip_code="90001")
Address.objects.create(customer=customer3, street="789 Pine St", city="Chicago", state="IL", zip_code="60601")
Address.objects.create(customer=customer4, street="101 Cedar St", city="Houston", state="TX", zip_code="77001")
Address.objects.create(customer=customer5, street="202 Birch St", city="Miami", state="FL", zip_code="33101")
category1 = Category.objects.create(name="Electronics")
category2 = Category.objects.create(name="Books")
category3 = Category.objects.create(name="Clothing")
category4 = Category.objects.create(name="Home Appliances")
category5 = Category.objects.create(name="Toys")
product1 = Product.objects.create(name="Smartphone", price=699.99, category=category1)
product2 = Product.objects.create(name="Laptop", price=1199.99, category=category1)
product3 = Product.objects.create(name="Fiction Book", price=19.99, category=category2)
product4 = Product.objects.create(name="T-shirt", price=9.99, category=category3)
product5 = Product.objects.create(name="Blender", price=49.99, category=category4)
product6 = Product.objects.create(name="Action Figure", price=24.99, category=category5)
product7 = Product.objects.create(name="Headphones", price=99.99, category=category1)
product8 = Product.objects.create(name="Cookbook", price=29.99, category=category2)
product9 = Product.objects.create(name="Jeans", price=39.99, category=category3)
product10 = Product.objects.create(name="Vacuum Cleaner", price=199.99, category=category4)
order1 = Order.objects.create(customer=customer1)
order1.products.add(product1, product3, product5)
order1.calculate_total_price()

order2 = Order.objects.create(customer=customer2)
order2.products.add(product2, product4, product6)
order2.calculate_total_price()

order3 = Order.objects.create(customer=customer3)
order3.products.add(product7, product8, product9)
order3.calculate_total_price()

order4 = Order.objects.create(customer=customer4)
order4.products.add(product10, product1, product2)
order4.calculate_total_price()

order5 = Order.objects.create(customer=customer5)
order5.products.add(product3, product5, product7, product9)
order5.calculate_total_price()

print(" Sample data inserted successfully!")
